config/routes.rb
Rails.application.routes.draw do
  resources :artists

  resources :bands

  mount Dashing::Engine, at: Dashing.config.engine_path

  root 'dashing/dashboards#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/band.rb
class Band < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < InheritedResources::Base

  private

    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :genre, :instrument, :location, :stage_name)
    end
end

app/controllers/bands_controller.rb
class BandsController < InheritedResources::Base

  private

    def band_params
      params.require(:band).permit(:band_name, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :genre %>
    <%= f.input :instrument %>
    <%= f.input :location %>
    <%= f.input :stage_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Genre</th>
      <th>Instrument</th>
      <th>Location</th>
      <th>Stage name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.first_name %></td>
        <td><%= artist.last_name %></td>
        <td><%= artist.genre %></td>
        <td><%= artist.instrument %></td>
        <td><%= artist.location %></td>
        <td><%= artist.stage_name %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @artist.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @artist.last_name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @artist.instrument %>
</p>

<p>
  <strong>Location:</strong>
  <%= @artist.location %>
</p>

<p>
  <strong>Stage name:</strong>
  <%= @artist.stage_name %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/bands/_form.html.erb
<%= simple_form_for(@band) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :band_name %>
    <%= f.input :genre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th>Band name</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.band_name %></td>
        <td><%= band.genre %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Band name:</strong>
  <%= @band.band_name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @band.genre %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/dashing/dashboards/artist.html.erb
<% content_for :artist do %>Bands<% end %>
<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="Welcome Artist!" data-moreinfo="Lets match you up!"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="synergy" data-view="Meter" data-title="Bands interested in you" data-min="0" data-max="10"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Hot Lyrics" data-moreinfo="# of times lyrics mentioned on Rdio "></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Streaming Revenue" data-moreinfo="In billions" data-prefix="$"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="twitter_mentions" data-view="Comments" data-title="Your Twitter Following" style="background-color:#4099FF;" data-moreinfo="Tweets tagged with #SeekingArtists!" </div>
      <i class="icon-twitter icon-background"></i>
    </li>
  </ul>

   <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="twitter_mentions" data-view="Comments" style="background-color:#ff9618;" data-moreinfo="Tweets tagged with #sxswhackathon"></div>
      <i class="icon-twitter icon-background"></i>
    </li>

</div>

app/views/dashing/dashboards/band.html.erb
<% content_for :bands do %>Bands<% end %>
<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="Band Dashboard" data-moreinfo="Lets see who you are match up today"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="synergy" data-view="Meter" data-title="Artist Interested in You" data-min="0" data-max="100"></div>
    </li>


     <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="twitter_mentions" data-view="Comments" style="background-color:#4099FF;" data-title="Your Twitter Following" data-moreinfo="Tweets tagged with #yourband" </div>
      <i class="icon-twitter icon-background"></i>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Valuation" data-moreinfo="In billions" data-prefix="$"></div>
    </li>

    <li data-row="2" data-col="3" data-sizex="2" data-sizey="1">
      <div data-id="convergence" data-view="Graph" data-title="Rdio Profile Views" style="background-color:#008fd5"></div>
    </li>
  </ul>

</div>

app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  Welcome
<% end %>

<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="Welcome" data-view="Text" data-title="Welcome to Lets Jam!" data-text="Lets find and audition your next band" data-moreinfo="Find the talent and get back to Jamming! ">
    </div>
    </li>

    <li data-row="2" data-col="1" data-sizex="1" data-sizey="1" onclick="location.href='http://localhost:3000/dashing/dashboards/lessons';">
      <div data-id="Artists" data-view="Text" data-title="Artists" data-text="If you are looking for a band " data-moreinfo="Sign up/in Here" style="background-color: #EF2A2A"> </div>
    </li>

    <li data-row="2" data-col="1" data-sizex="1" data-sizey="1" onclick="location.href='http://localhost:3000/dashing/dashboards/band';">
    <div data-id="Bands" data-view="Text" data-title="Bands" data-text="If you are looking for an Artist to Join your group " data-moreinfo="Sign up/in Here" style="background-color: #3136A6"> </div>
    <li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Hot Artist" data-moreinfo="# and growing" style="background-color: #EFDF2A"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Artist and Banding looking to meet" data-moreinfo="In billions"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Hot Tracks"  data-moreinfo="# of times said in Slack"style="background-color:#128FFF"></div>
    </li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letsjam2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= yield :title %></title>

    <%= javascript_include_tag 'dashing/application' %>
    <%= stylesheet_link_tag 'dashing/application' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="/favicon.ico">
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
      <div id="saving-instructions">
        <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
        <textarea id="gridster-code"></textarea>
      </div>
      <a href="#saving-instructions" id="save-gridster">Save this layout</a>
    <% end %>
  </body>
</html>